Overhaul scripts and GitHub Actions workflows to auto-detect the operating system; use num_cpus scripts; use build.ps1 and test.ps1 scripts instead of lukka/run-cmake action; and FORCE_JAVASCRIPT_ACTIONS_TO_NODE24, except on Hetzner runners

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # The MIT License (MIT)
 #
-# Copyright © 2023-2025 Stephen G. Tuggy
+# Copyright © 2023-2026 Stephen G. Tuggy
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the “Software”), to deal
@@ -24,7 +24,7 @@
 set -e
 
 echo "--------------------------"
-echo "--- build | 2025-06-27 ---"
+echo "--- build | 2026-04-29 ---"
 echo "--------------------------"
 
 #----------------------------------
@@ -54,14 +54,35 @@ while [ $# -gt 0 ]; do
   shift
 done
 
+ROOT_DIR=$(pwd)
+echo "ROOT_DIR: ${ROOT_DIR}"
+BUILD_DIR="${ROOT_DIR}/build"
+echo "BUILD_DIR: ${BUILD_DIR}"
+BIN_DIR="${ROOT_DIR}/bin"
+
+# -p creates if the target doesn't exist, noop otherwise
+mkdir -pv "${BUILD_DIR}"
+
 cmake --preset "$preset_name"
 
-MAX_THREADS_TO_BUILD_WITH=8
-num_threads_to_build_with=$(getconf _NPROCESSORS_ONLN)
-if [ ${num_threads_to_build_with} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
+MAX_THREADS_TO_BUILD_WITH=6
+if [ -f ./script/num_cpus ] && [ -x ./script/num_cpus ]
 then
-    num_threads_to_build_with=${MAX_THREADS_TO_BUILD_WITH}
+  num_threads_to_build_with=$(./script/num_cpus)
+elif [ -f ./num_cpus ] && [ -x ./num_cpus ]
+then
+  num_threads_to_build_with=$(./num_cpus)
+else
+  echo "Error locating num_cpus script"
+  exit 3
 fi
 
+echo "Number of threads to build with before capping: $num_threads_to_build_with"
+if [ ${num_threads_to_build_with} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
+then
+  num_threads_to_build_with=${MAX_THREADS_TO_BUILD_WITH}
+fi
+echo "Number of threads to build with after capping: $num_threads_to_build_with"
 echo "Preset name is $preset_name"
-VERBOSE=1 cmake --build --preset "build-$preset_name" -j ${num_threads_to_build_with}
+
+VERBOSE=1 cmake --build --preset="build-${preset_name}" -j ${num_threads_to_build_with}
